<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="HBADT4950189" name="com.qa.testscripts.readDashboardHeadingTC10andTC11andTC12" tests="5" failures="1" timestamp="12 Mar 2021 11:08:37 GMT" time="10.444" errors="0">
  <testcase name="readDashboardAndtakeCaptureDashboardMenu" time="4.056" classname="com.qa.testscripts.readDashboardHeadingTC10andTC11andTC12"/>
  <testcase name="retryAnalyzerDashboardMenu" time="1.735" classname="com.qa.testscripts.readDashboardHeadingTC10andTC11andTC12">
    <skipped/>
  </testcase> <!-- retryAnalyzerDashboardMenu -->
  <testcase name="retryAnalyzerDashboardMenu" time="1.057" classname="com.qa.testscripts.readDashboardHeadingTC10andTC11andTC12">
    <skipped/>
  </testcase> <!-- retryAnalyzerDashboardMenu -->
  <testcase name="retryAnalyzerDashboardMenu" time="1.802" classname="com.qa.testscripts.readDashboardHeadingTC10andTC11andTC12">
    <skipped/>
  </testcase> <!-- retryAnalyzerDashboardMenu -->
  <testcase name="retryAnalyzerDashboardMenu" time="1.794" classname="com.qa.testscripts.readDashboardHeadingTC10andTC11andTC12">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.qa.testscripts.readDashboardHeadingTC10andTC11andTC12.retryAnalyzerDashboardMenu(readDashboardHeadingTC10andTC11andTC12.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- retryAnalyzerDashboardMenu -->
</testsuite> <!-- com.qa.testscripts.readDashboardHeadingTC10andTC11andTC12 -->
